# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attack.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x61ttack.proto\"*\n\x13\x46indAMachineRequest\x12\x13\n\x0bsubnetMasks\x18\x01 \x01(\t\"&\n\x12MachinesUpResponse\x12\x10\n\x08machines\x18\x01 \x03(\t\"G\n\x19\x46ingerPrintMachineRequest\x12\x13\n\x0bportsToScan\x18\x01 \x03(\x05\x12\x15\n\ractiveMachine\x18\x02 \x01(\t\"#\n\x13\x46ingerPrintResponse\x12\x0c\n\x04port\x18\x01 \x03(\t\"C\n\x11GainAccessRequest\x12\x1a\n\x12machineInformation\x18\x01 \x03(\t\x12\x12\n\ntargetHost\x18\x02 \x01(\t\"`\n\x12GainAccessResponse\x12\x14\n\x0cgainedAccess\x18\x01 \x01(\x08\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ssMethod\x18\x04 \x01(\t\"[\n\x12\x41\x64\x64\x42\x61\x63kdoorRequest\x12\x17\n\x0f\x62\x61\x63kdoorCommand\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\"6\n\x13\x41\x64\x64\x42\x61\x63kdoorResponse\x12\x1f\n\x17\x62\x61\x63kdoorCommandResponse\x18\x01 \x01(\t\"[\n\x14TriggerAttackRequest\x12\x15\n\rattackCommand\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\"/\n\x15TriggerAttackResponse\x12\x16\n\x0e\x61ttackResponse\x18\x01 \x01(\t\"(\n\x12\x43learTracksRequest\x12\x12\n\nremoveLogs\x18\x01 \x01(\x08\"7\n\x13\x43learTracksResponse\x12 \n\x18removeLogCommandResponse\x18\x01 \x01(\t2\xef\x02\n\x06\x41ttack\x12\x39\n\x0c\x46indAMachine\x12\x14.FindAMachineRequest\x1a\x13.MachinesUpResponse\x12?\n\x0b\x46ingerPrint\x12\x1a.FingerPrintMachineRequest\x1a\x14.FingerPrintResponse\x12\x35\n\nGainAccess\x12\x12.GainAccessRequest\x1a\x13.GainAccessResponse\x12\x38\n\x0b\x41\x64\x64\x42\x61\x63kdoor\x12\x13.AddBackdoorRequest\x1a\x14.AddBackdoorResponse\x12>\n\rTriggerAttack\x12\x15.TriggerAttackRequest\x1a\x16.TriggerAttackResponse\x12\x38\n\x0b\x43learTracks\x12\x13.ClearTracksRequest\x1a\x14.ClearTracksResponseb\x06proto3'
)




_FINDAMACHINEREQUEST = _descriptor.Descriptor(
  name='FindAMachineRequest',
  full_name='FindAMachineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subnetMasks', full_name='FindAMachineRequest.subnetMasks', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=58,
)


_MACHINESUPRESPONSE = _descriptor.Descriptor(
  name='MachinesUpResponse',
  full_name='MachinesUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machines', full_name='MachinesUpResponse.machines', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=98,
)


_FINGERPRINTMACHINEREQUEST = _descriptor.Descriptor(
  name='FingerPrintMachineRequest',
  full_name='FingerPrintMachineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='portsToScan', full_name='FingerPrintMachineRequest.portsToScan', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeMachine', full_name='FingerPrintMachineRequest.activeMachine', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=171,
)


_FINGERPRINTRESPONSE = _descriptor.Descriptor(
  name='FingerPrintResponse',
  full_name='FingerPrintResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='FingerPrintResponse.port', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=208,
)


_GAINACCESSREQUEST = _descriptor.Descriptor(
  name='GainAccessRequest',
  full_name='GainAccessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machineInformation', full_name='GainAccessRequest.machineInformation', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetHost', full_name='GainAccessRequest.targetHost', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=277,
)


_GAINACCESSRESPONSE = _descriptor.Descriptor(
  name='GainAccessResponse',
  full_name='GainAccessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gainedAccess', full_name='GainAccessResponse.gainedAccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='GainAccessResponse.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='GainAccessResponse.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accessMethod', full_name='GainAccessResponse.accessMethod', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=375,
)


_ADDBACKDOORREQUEST = _descriptor.Descriptor(
  name='AddBackdoorRequest',
  full_name='AddBackdoorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backdoorCommand', full_name='AddBackdoorRequest.backdoorCommand', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='AddBackdoorRequest.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='AddBackdoorRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='AddBackdoorRequest.host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=468,
)


_ADDBACKDOORRESPONSE = _descriptor.Descriptor(
  name='AddBackdoorResponse',
  full_name='AddBackdoorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backdoorCommandResponse', full_name='AddBackdoorResponse.backdoorCommandResponse', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=524,
)


_TRIGGERATTACKREQUEST = _descriptor.Descriptor(
  name='TriggerAttackRequest',
  full_name='TriggerAttackRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attackCommand', full_name='TriggerAttackRequest.attackCommand', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='TriggerAttackRequest.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='TriggerAttackRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='TriggerAttackRequest.host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=617,
)


_TRIGGERATTACKRESPONSE = _descriptor.Descriptor(
  name='TriggerAttackResponse',
  full_name='TriggerAttackResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attackResponse', full_name='TriggerAttackResponse.attackResponse', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=666,
)


_CLEARTRACKSREQUEST = _descriptor.Descriptor(
  name='ClearTracksRequest',
  full_name='ClearTracksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='removeLogs', full_name='ClearTracksRequest.removeLogs', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=708,
)


_CLEARTRACKSRESPONSE = _descriptor.Descriptor(
  name='ClearTracksResponse',
  full_name='ClearTracksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='removeLogCommandResponse', full_name='ClearTracksResponse.removeLogCommandResponse', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=710,
  serialized_end=765,
)

DESCRIPTOR.message_types_by_name['FindAMachineRequest'] = _FINDAMACHINEREQUEST
DESCRIPTOR.message_types_by_name['MachinesUpResponse'] = _MACHINESUPRESPONSE
DESCRIPTOR.message_types_by_name['FingerPrintMachineRequest'] = _FINGERPRINTMACHINEREQUEST
DESCRIPTOR.message_types_by_name['FingerPrintResponse'] = _FINGERPRINTRESPONSE
DESCRIPTOR.message_types_by_name['GainAccessRequest'] = _GAINACCESSREQUEST
DESCRIPTOR.message_types_by_name['GainAccessResponse'] = _GAINACCESSRESPONSE
DESCRIPTOR.message_types_by_name['AddBackdoorRequest'] = _ADDBACKDOORREQUEST
DESCRIPTOR.message_types_by_name['AddBackdoorResponse'] = _ADDBACKDOORRESPONSE
DESCRIPTOR.message_types_by_name['TriggerAttackRequest'] = _TRIGGERATTACKREQUEST
DESCRIPTOR.message_types_by_name['TriggerAttackResponse'] = _TRIGGERATTACKRESPONSE
DESCRIPTOR.message_types_by_name['ClearTracksRequest'] = _CLEARTRACKSREQUEST
DESCRIPTOR.message_types_by_name['ClearTracksResponse'] = _CLEARTRACKSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindAMachineRequest = _reflection.GeneratedProtocolMessageType('FindAMachineRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDAMACHINEREQUEST,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:FindAMachineRequest)
  })
_sym_db.RegisterMessage(FindAMachineRequest)

MachinesUpResponse = _reflection.GeneratedProtocolMessageType('MachinesUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _MACHINESUPRESPONSE,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:MachinesUpResponse)
  })
_sym_db.RegisterMessage(MachinesUpResponse)

FingerPrintMachineRequest = _reflection.GeneratedProtocolMessageType('FingerPrintMachineRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINGERPRINTMACHINEREQUEST,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:FingerPrintMachineRequest)
  })
_sym_db.RegisterMessage(FingerPrintMachineRequest)

FingerPrintResponse = _reflection.GeneratedProtocolMessageType('FingerPrintResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINGERPRINTRESPONSE,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:FingerPrintResponse)
  })
_sym_db.RegisterMessage(FingerPrintResponse)

GainAccessRequest = _reflection.GeneratedProtocolMessageType('GainAccessRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAINACCESSREQUEST,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:GainAccessRequest)
  })
_sym_db.RegisterMessage(GainAccessRequest)

GainAccessResponse = _reflection.GeneratedProtocolMessageType('GainAccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAINACCESSRESPONSE,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:GainAccessResponse)
  })
_sym_db.RegisterMessage(GainAccessResponse)

AddBackdoorRequest = _reflection.GeneratedProtocolMessageType('AddBackdoorRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDBACKDOORREQUEST,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:AddBackdoorRequest)
  })
_sym_db.RegisterMessage(AddBackdoorRequest)

AddBackdoorResponse = _reflection.GeneratedProtocolMessageType('AddBackdoorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDBACKDOORRESPONSE,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:AddBackdoorResponse)
  })
_sym_db.RegisterMessage(AddBackdoorResponse)

TriggerAttackRequest = _reflection.GeneratedProtocolMessageType('TriggerAttackRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRIGGERATTACKREQUEST,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:TriggerAttackRequest)
  })
_sym_db.RegisterMessage(TriggerAttackRequest)

TriggerAttackResponse = _reflection.GeneratedProtocolMessageType('TriggerAttackResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRIGGERATTACKRESPONSE,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:TriggerAttackResponse)
  })
_sym_db.RegisterMessage(TriggerAttackResponse)

ClearTracksRequest = _reflection.GeneratedProtocolMessageType('ClearTracksRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARTRACKSREQUEST,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:ClearTracksRequest)
  })
_sym_db.RegisterMessage(ClearTracksRequest)

ClearTracksResponse = _reflection.GeneratedProtocolMessageType('ClearTracksResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLEARTRACKSRESPONSE,
  '__module__' : 'attack_pb2'
  # @@protoc_insertion_point(class_scope:ClearTracksResponse)
  })
_sym_db.RegisterMessage(ClearTracksResponse)



_ATTACK = _descriptor.ServiceDescriptor(
  name='Attack',
  full_name='Attack',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=768,
  serialized_end=1135,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindAMachine',
    full_name='Attack.FindAMachine',
    index=0,
    containing_service=None,
    input_type=_FINDAMACHINEREQUEST,
    output_type=_MACHINESUPRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FingerPrint',
    full_name='Attack.FingerPrint',
    index=1,
    containing_service=None,
    input_type=_FINGERPRINTMACHINEREQUEST,
    output_type=_FINGERPRINTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GainAccess',
    full_name='Attack.GainAccess',
    index=2,
    containing_service=None,
    input_type=_GAINACCESSREQUEST,
    output_type=_GAINACCESSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddBackdoor',
    full_name='Attack.AddBackdoor',
    index=3,
    containing_service=None,
    input_type=_ADDBACKDOORREQUEST,
    output_type=_ADDBACKDOORRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TriggerAttack',
    full_name='Attack.TriggerAttack',
    index=4,
    containing_service=None,
    input_type=_TRIGGERATTACKREQUEST,
    output_type=_TRIGGERATTACKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClearTracks',
    full_name='Attack.ClearTracks',
    index=5,
    containing_service=None,
    input_type=_CLEARTRACKSREQUEST,
    output_type=_CLEARTRACKSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ATTACK)

DESCRIPTOR.services_by_name['Attack'] = _ATTACK

# @@protoc_insertion_point(module_scope)
